# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Development Build

on: [push]

jobs:
  composer-update:
    runs-on: ubuntu-latest
    steps:
      - name: Update composer
        run: |
          curl -XPOST -H'content-type:application/json' 'https://packagist.org/api/update-package?username=denanu&apiToken=${{ secrets.COMPOSER_API }}' -d'{"repository":{"url":"https://github.com/JulianWww/denanu-login/"}}'